name: CI

on:
  push:
  pull_request:

jobs:
  test:
    run-on: ubuntu-latest

    steps:
      - names: checkout to a repository
        uses: action/checkout@v4

      - names: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - names: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - names: run the tests
        run: pytest -q
